### ISSUE TITLE
TypeError: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by NyaomiDEV** [danik4985/sus#2]
I cannot obfuscate a test file that just outputs "amogus"

sus-obfuscator v1.3.0 installed globally

```
% sus -i hello.js -o sus.js --verbose
Starting obfuscation of hello.js
Verbose: true
Plase be patient...
[i] Config: {
  ignore: [],
  removeEmptyLines: true,
  shrink: true,
  amogus: [ true, false ],
  lineStart: false,
  epicEndArt: true
}
[i] 0 { type: 'IdentifierName', value: 'console' }
/home/naomi/.config/yarn/global/node_modules/sus-obfuscator/main.js:95
        && tokens[(n - 1)].value != '.'
                           ^

TypeError: Cannot read property 'value' of undefined
    at /home/naomi/.config/yarn/global/node_modules/sus-obfuscator/main.js:95:28
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/naomi/.config/yarn/global/node_modules/sus-obfuscator/main.js:90:8)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
```

the test file:
```
console.log("amogus")
```

**Comment by danik4985** [comment]
Hello,
thank you for reporting the issue. I have fixed it now and it should no longer appear in the next release.

**Comment by danik4985** [comment]
# Workaround
Add a new line to the start of the file, so it looks like this:
```js
    
console.log("amogus")
```
This seems to work. I am working on the next release where this should no longer be needed since this issue will be fixed.
